### ISSUE TITLE
[Feat] : 가게 정보 기능 구현

### ISSUE THREAD

**Issue by PIYUJIN** [Kusitms-Hackathon-C/kusitms-hackathon-c#17]
## 설명
가게 정보 마커 표시 및 상세 정보 기능 구현

## To-Do List
- [ ] 가게 위치 마커 표시
- [ ] bottom sheet layout 구성
- [ ] 가게 정보 API 연결 기능 구현
- [ ] 가게 상세 정보 화면 연결
